### PR TITLE
re-render

### PR DESCRIPTION
**Pull request by CJ-Wright**
and sync with lightsource2
Sorry for the master to master PR

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@conda-forge/doct ready for review!

**Comment by ericdill** [comment]
ugh how am I the only owner of this

**Comment by ericdill** [comment]
thanks for adding yourself @CJ-Wright !

**Comment by ericdill** [comment]
can you add @tacaswell  and @danielballan while you're in here @CJ-Wright ?

**Comment by ericdill** [comment]
probably wanted to add [skip ci] on that last commit :)

**Comment by CJ-Wright** [comment]
oops

**Comment by CJ-Wright** [comment]
Can I force commit a skip?

**Comment by ericdill** [comment]
Manually cancelling the CI services has the same effect

**Comment by CJ-Wright** [comment]
either way it is ready. @tacaswell @danielballan @licode are you all on board with being on this?

**Comment by ericdill** [comment]
muahaha no chance! no but seriously I've already been granted carte blanche from @tacaswell and @licode to add them to recipes as per https://github.com/conda-forge/staged-recipes/issues/139.

**Comment by CJ-Wright** [comment]
Thank you!

**Pull request merged**
